/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import InlineResponse404 from '../InlineResponse404';
import Vendor from '../Vendor';

/**
* Vendors service.
* @module VendorsApi
* @version 1.67
*/
export default class VendorsApi {

    /**
    * Constructs a new VendorsApi. 
    * @alias module:VendorsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getAllvendors operation.
     * @callback module:VendorsApi~getAllvendorsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:Vendor>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * fetchs all vendor records
     * endpoint to get an array of all vendor records
     * @param {module:VendorsApi~getAllvendorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:Vendor>}
     */
    getAllvendors() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Vendor];

      return this.apiClient.callApi(
        '/store/vendors', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getVendor operation.
     * @callback module:VendorsApi~getVendorCallback
     * @param {String} error Error message, if any.
     * @param {module:Vendor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get user record by id
     * endpoint to get a single vendor record
     * @param {module:VendorsApi~getVendorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Vendor}
     */
    getVendor() {
      let postBody = null;

      let pathParams = {
        'vendorid': vendorid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Vendor;

      return this.apiClient.callApi(
        '/store/vendors/{vendorid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateVendor operation.
     * @callback module:VendorsApi~updateVendorCallback
     * @param {String} error Error message, if any.
     * @param {module:Vendor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update vendor record by id
     * endpoint to update a single vendor record
     * @param {Object} opts Optional parameters
     * @param {module:VendorsApi~updateVendorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Vendor}
     */
    updateVendor() {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'vendorid': vendorid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic'];
      let contentTypes = ['application/json', 'mulipart/formdata', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = Vendor;

      return this.apiClient.callApi(
        '/store/vendors/{vendorid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
